# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from gb_retailapi_client.models.product_dto import ProductDto  # noqa: E501

class TestProductDto(unittest.TestCase):
    """ProductDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductDto:
        """Test ProductDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductDto`
        """
        model = ProductDto()  # noqa: E501
        if include_optional:
            return ProductDto(
                name = 'projects/123456789012/locations/global/catalogs/default_catalog/branches/1/products/12345678901',
                id = '12345678901',
                type = 'VARIANT, PRIMARY',
                primary_product_id = '1234567',
                collection_member_ids = 5,
                gtin = '10614141999993',
                categories = Men, Men > Shoes,
                title = 'Eastland Shoe Men's Yarmouth Boat Shoes',
                brands = Eastland Shoe,
                description = 'Eastland Shoe recalls an age of timeless casual fashion with these leather boat shoes.',
                language_code = 'en-US',
                attributes = { 'vendor': {'text': ['vendor123', 'vendor456']}, 'lengths_cm': {'numbers':[2.3, 15.4]}, 'heights_cm': {'numbers':[8.1, 6.4]}},
                tags = Any string.,
                price_info = None,
                rating = None,
                available_time = None,
                availability = 'IN_STOCK',
                available_quantity = 10,
                fulfillment_infos = [
                    gb_retailapi_client.models.fulfillment_info.FulfillmentInfo(
                        type = 'pickup-in-store', 
                        place_ids = 6, 4, 8, )
                    ],
                uri = 'https://s4r-apparel.groupby.cloud/product/Eastland-Shoe-Men's-Yarmouth-Boat-Shoes/2725066/94352309386',
                images = [
                    gb_retailapi_client.models.image.Image(
                        uri = 'https://storage.googleapis.com/poc_apparel/images/1/optimized/3412471_fpx.tif', 
                        height = 150, 
                        width = 150, )
                    ],
                audience = None,
                color_info = None,
                sizes = 8.5,
                materials = leather,
                patterns = paisley,
                conditions = new,
                publish_time = None,
                retrievable_fields = None,
                promotions = [
                    gb_retailapi_client.models.promotion.Promotion(
                        promotion_id = 'id0LikeThis', )
                    ],
                variants = [
                    gb_retailapi_client.models.product.Product(
                        name = 'projects/123456789012/locations/global/catalogs/default_catalog/branches/1/products/12345678901', 
                        id = '12345678901', 
                        type = 'VARIANT, PRIMARY', 
                        primary_product_id = '1234567', 
                        collection_member_ids = 5, 
                        gtin = '10614141999993', 
                        categories = Men, Men > Shoes, 
                        title = 'Eastland Shoe Men's Yarmouth Boat Shoes', 
                        brands = Eastland Shoe, 
                        description = 'Eastland Shoe recalls an age of timeless casual fashion with these leather boat shoes.', 
                        language_code = 'en-US', 
                        attributes = { 'vendor': {'text': ['vendor123', 'vendor456']}, 'lengths_cm': {'numbers':[2.3, 15.4]}, 'heights_cm': {'numbers':[8.1, 6.4]}}, 
                        tags = Any string., 
                        price_info = null, 
                        rating = null, 
                        available_time = null, 
                        availability = 'IN_STOCK', 
                        available_quantity = 10, 
                        fulfillment_infos = [
                            gb_retailapi_client.models.fulfillment_info.FulfillmentInfo(
                                type = 'pickup-in-store', 
                                place_ids = 6, 4, 8, )
                            ], 
                        uri = 'https://s4r-apparel.groupby.cloud/product/Eastland-Shoe-Men's-Yarmouth-Boat-Shoes/2725066/94352309386', 
                        images = [
                            gb_retailapi_client.models.image.Image(
                                uri = 'https://storage.googleapis.com/poc_apparel/images/1/optimized/3412471_fpx.tif', 
                                height = 150, 
                                width = 150, )
                            ], 
                        audience = null, 
                        color_info = null, 
                        sizes = 8.5, 
                        materials = leather, 
                        patterns = paisley, 
                        conditions = new, 
                        publish_time = null, 
                        retrievable_fields = null, 
                        promotions = [
                            gb_retailapi_client.models.promotion.Promotion(
                                promotion_id = 'id0LikeThis', )
                            ], 
                        variants = [
                            gb_retailapi_client.models.product.Product(
                                name = 'projects/123456789012/locations/global/catalogs/default_catalog/branches/1/products/12345678901', 
                                id = '12345678901', 
                                type = 'VARIANT, PRIMARY', 
                                primary_product_id = '1234567', 
                                collection_member_ids = 5, 
                                gtin = '10614141999993', 
                                categories = Men, Men > Shoes, 
                                title = 'Eastland Shoe Men's Yarmouth Boat Shoes', 
                                brands = Eastland Shoe, 
                                description = 'Eastland Shoe recalls an age of timeless casual fashion with these leather boat shoes.', 
                                language_code = 'en-US', 
                                attributes = { 'vendor': {'text': ['vendor123', 'vendor456']}, 'lengths_cm': {'numbers':[2.3, 15.4]}, 'heights_cm': {'numbers':[8.1, 6.4]}}, 
                                tags = Any string., 
                                availability = 'IN_STOCK', 
                                available_quantity = 10, 
                                uri = 'https://s4r-apparel.groupby.cloud/product/Eastland-Shoe-Men's-Yarmouth-Boat-Shoes/2725066/94352309386', 
                                sizes = 8.5, 
                                materials = leather, 
                                patterns = paisley, 
                                conditions = new, )
                            ], )
                    ]
            )
        else:
            return ProductDto(
        )
        """

    def testProductDto(self):
        """Test ProductDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
