# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gb_retailapi_client.api.autocomplete_api import AutocompleteApi  # noqa: E501


class TestAutocompleteApi(unittest.TestCase):
    """AutocompleteApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AutocompleteApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_autocompletesearch(self) -> None:
        """Test case for autocompletesearch

        """
        pass


if __name__ == '__main__':
    unittest.main()
