# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gb_retailapi_client.api.product_api import ProductApi  # noqa: E501


class TestProductApi(unittest.TestCase):
    """ProductApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProductApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_by_product_ids(self) -> None:
        """Test case for get_by_product_ids

        Provided product search functionality  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
