# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from gb_retailapi_client.models.message_type import MessageType  # noqa: E501

class TestMessageType(unittest.TestCase):
    """MessageType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMessageType(self):
        """Test MessageType"""
        # inst = MessageType()

if __name__ == '__main__':
    unittest.main()
