# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from gb_retailapi_client.models.rule_template_section import RuleTemplateSection  # noqa: E501

class TestRuleTemplateSection(unittest.TestCase):
    """RuleTemplateSection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RuleTemplateSection:
        """Test RuleTemplateSection
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RuleTemplateSection`
        """
        model = RuleTemplateSection()  # noqa: E501
        if include_optional:
            return RuleTemplateSection(
                zone_id = 56,
                name = '',
                zone_content = '',
                zone_type = 'QUERY'
            )
        else:
            return RuleTemplateSection(
                zone_id = 56,
                name = '',
                zone_content = '',
                zone_type = 'QUERY',
        )
        """

    def testRuleTemplateSection(self):
        """Test RuleTemplateSection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
