# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from gb_retailapi_client.models.record_dto import RecordDto  # noqa: E501

class TestRecordDto(unittest.TestCase):
    """RecordDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecordDto:
        """Test RecordDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecordDto`
        """
        model = RecordDto()  # noqa: E501
        if include_optional:
            return RecordDto(
                id = '2cfcf5443046e6733a40608af8a35c95',
                u = 'http://apparel1productsClothing.com/12345',
                t = '3/4 length shorts',
                collection = 'productsClothing',
                all_meta = { }
            )
        else:
            return RecordDto(
        )
        """

    def testRecordDto(self):
        """Test RecordDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
