# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from gb_retailapi_client.models.template_dto import TemplateDto  # noqa: E501

class TestTemplateDto(unittest.TestCase):
    """TemplateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemplateDto:
        """Test TemplateDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplateDto`
        """
        model = TemplateDto()  # noqa: E501
        if include_optional:
            return TemplateDto(
                name = 'default',
                rule_name = 'Easter Sale 2021',
                trigger_set = None,
                zones = [
                    gb_retailapi_client.models.zone.Zone(
                        name = 'any string', 
                        type = null, 
                        content = 'any string', 
                        rich_content = 'any string', )
                    ]
            )
        else:
            return TemplateDto(
        )
        """

    def testTemplateDto(self):
        """Test TemplateDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
