# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gb_retailapi_client.api.recommendations_api_api import RecommendationsAPIApi  # noqa: E501


class TestRecommendationsAPIApi(unittest.TestCase):
    """RecommendationsAPIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecommendationsAPIApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_predict(self) -> None:
        """Test case for predict

        Provide Recommendations AI functionality.  # noqa: E501
        """
        pass

    def test_predict_v2(self) -> None:
        """Test case for predict_v2

        Provide Recommendations AI functionality.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
