# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from gb_retailapi_client.models.product_dto_color_info import ProductDtoColorInfo  # noqa: E501

class TestProductDtoColorInfo(unittest.TestCase):
    """ProductDtoColorInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductDtoColorInfo:
        """Test ProductDtoColorInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductDtoColorInfo`
        """
        model = ProductDtoColorInfo()  # noqa: E501
        if include_optional:
            return ProductDtoColorInfo(
                color_families = Blue,
                colors = Navy
            )
        else:
            return ProductDtoColorInfo(
        )
        """

    def testProductDtoColorInfo(self):
        """Test ProductDtoColorInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
