# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from gb_retailapi_client.models.zone_type import ZoneType  # noqa: E501

class TestZoneType(unittest.TestCase):
    """ZoneType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testZoneType(self):
        """Test ZoneType"""
        # inst = ZoneType()

if __name__ == '__main__':
    unittest.main()
