# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from gb_retailapi_client.models.spell_correction_mode import SpellCorrectionMode  # noqa: E501

class TestSpellCorrectionMode(unittest.TestCase):
    """SpellCorrectionMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpellCorrectionMode(self):
        """Test SpellCorrectionMode"""
        # inst = SpellCorrectionMode()

if __name__ == '__main__':
    unittest.main()
