# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from gb_retailapi_client.models.recommendations_request import RecommendationsRequest  # noqa: E501

class TestRecommendationsRequest(unittest.TestCase):
    """RecommendationsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecommendationsRequest:
        """Test RecommendationsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecommendationsRequest`
        """
        model = RecommendationsRequest()  # noqa: E501
        if include_optional:
            return RecommendationsRequest(
                collection = '0',
                visitor_id = '',
                limit = '',
                page_size = '',
                event_type = '',
                login_id = '',
                product_id = [
                    ''
                    ],
                fields = [
                    ''
                    ],
                filters = [
                    gb_retailapi_client.models.filter.Filter(
                        field = '0', 
                        value = '', 
                        exclude = True, 
                        derived_from_product = True, )
                    ],
                raw_filter = '',
                placement = '',
                name = '',
                strict_filtering = True
            )
        else:
            return RecommendationsRequest(
                collection = '0',
        )
        """

    def testRecommendationsRequest(self):
        """Test RecommendationsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
