# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from gb_retailapi_client.models.product_dto_audience import ProductDtoAudience  # noqa: E501

class TestProductDtoAudience(unittest.TestCase):
    """ProductDtoAudience unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductDtoAudience:
        """Test ProductDtoAudience
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductDtoAudience`
        """
        model = ProductDtoAudience()  # noqa: E501
        if include_optional:
            return ProductDtoAudience(
                genders = unisex,
                age_groups = newborn
            )
        else:
            return ProductDtoAudience(
        )
        """

    def testProductDtoAudience(self):
        """Test ProductDtoAudience"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
