# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gb_retailapi_client.api.search_api import SearchApi  # noqa: E501


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SearchApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_facet_search(self) -> None:
        """Test case for facet_search

        Provided search functionality  # noqa: E501
        """
        pass

    def test_search(self) -> None:
        """Test case for search

        Provided search functionality  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
