# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from gb_retailapi_client.models.selected_refinement_dto import SelectedRefinementDto  # noqa: E501

class TestSelectedRefinementDto(unittest.TestCase):
    """SelectedRefinementDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SelectedRefinementDto:
        """Test SelectedRefinementDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SelectedRefinementDto`
        """
        model = SelectedRefinementDto()  # noqa: E501
        if include_optional:
            return SelectedRefinementDto(
                navigation_name = 'brands',
                type = None,
                value = '',
                low = 50,
                high = 100,
                source = 'Dynamic',
                var_or = False
            )
        else:
            return SelectedRefinementDto(
                navigation_name = 'brands',
                type = None,
        )
        """

    def testSelectedRefinementDto(self):
        """Test SelectedRefinementDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
