# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from gb_retailapi_client.models.navigation_type import NavigationType  # noqa: E501

class TestNavigationType(unittest.TestCase):
    """NavigationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNavigationType(self):
        """Test NavigationType"""
        # inst = NavigationType()

if __name__ == '__main__':
    unittest.main()
