# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from gb_retailapi_client.models.field_mask import FieldMask  # noqa: E501

class TestFieldMask(unittest.TestCase):
    """FieldMask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FieldMask:
        """Test FieldMask
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FieldMask`
        """
        model = FieldMask()  # noqa: E501
        if include_optional:
            return FieldMask(
                paths = color_info, price_info, audience, images, sizes, materials, name, availability, title, uri. When list is empty or "*" string exist in list -api will return all fields.
            )
        else:
            return FieldMask(
        )
        """

    def testFieldMask(self):
        """Test FieldMask"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
