# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from gb_retailapi_client.models.error_dto import ErrorDto  # noqa: E501

class TestErrorDto(unittest.TestCase):
    """ErrorDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ErrorDto:
        """Test ErrorDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ErrorDto`
        """
        model = ErrorDto()  # noqa: E501
        if include_optional:
            return ErrorDto(
                tracking_id = 'bb25d616-2cd7-44a1-8d11-27159f2aa03c',
                method = 'POST',
                path = '/api/v2/search',
                message = 'Search request page size must be greater than or equal to 0.'
            )
        else:
            return ErrorDto(
        )
        """

    def testErrorDto(self):
        """Test ErrorDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
