# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from gb_retailapi_client.models.request import Request  # noqa: E501

class TestRequest(unittest.TestCase):
    """Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Request:
        """Test Request
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Request`
        """
        model = Request()  # noqa: E501
        if include_optional:
            return Request(
                area = '',
                collection = '0',
                search_items = 1,
                query = '0',
                enable_attribute_suggestion = True,
                extended_suggestions = True,
                extended_attributes = [
                    ''
                    ],
                visitor_id = '',
                site = ''
            )
        else:
            return Request(
                area = '',
                collection = '0',
                search_items = 1,
                query = '0',
        )
        """

    def testRequest(self):
        """Test Request"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
