# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from gb_retailapi_client.models.overwrites import Overwrites  # noqa: E501

class TestOverwrites(unittest.TestCase):
    """Overwrites unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Overwrites:
        """Test Overwrites
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Overwrites`
        """
        model = Overwrites()  # noqa: E501
        if include_optional:
            return Overwrites(
                rules = [
                    gb_retailapi_client.models.rule_configuration.RuleConfiguration(
                        rule_in_experiment = True, 
                        id = 56, 
                        name = '', 
                        area_id = 56, 
                        priority = 56, 
                        enabled = True, 
                        active_hours_enabled = True, 
                        active_from = 56, 
                        active_to = 56, 
                        trigger_sets = [
                            gb_retailapi_client.models.trigger_set.TriggerSet(
                                query_pattern_triggers = [
                                    gb_retailapi_client.models.query_pattern_trigger.QueryPatternTrigger(
                                        type = 'CONTAINS', 
                                        values = [
                                            ''
                                            ], 
                                        patterns = [
                                            gb_retailapi_client.models.pattern.Pattern()
                                            ], )
                                    ], 
                                selected_refinement_triggers = [
                                    gb_retailapi_client.models.selected_refinement_trigger.SelectedRefinementTrigger(
                                        field = '', 
                                        value = '', 
                                        range = gb_retailapi_client.models.range.Range(
                                            low = 1.337, 
                                            high = 1.337, ), 
                                        type = 'RANGE', )
                                    ], 
                                custom_parameter_triggers = [
                                    gb_retailapi_client.models.custom_parameter_trigger.CustomParameterTrigger(
                                        key = '', 
                                        value = '', )
                                    ], )
                            ], 
                        biasing_profile_name = '', 
                        sort = gb_retailapi_client.models.sort.Sort(
                            field = '', 
                            order = null, ), 
                        included_navigations = [
                            ''
                            ], 
                        value_filters = [
                            gb_retailapi_client.models.value_filter.ValueFilter(
                                field = '', 
                                value = '', 
                                number_value = 1.337, 
                                exclude = True, 
                                type = null, )
                            ], 
                        search_filters = [
                            gb_retailapi_client.models.search_filter.SearchFilter(
                                value = '', )
                            ], 
                        range_filters = [
                            gb_retailapi_client.models.range_filter.RangeFilter(
                                field = '', 
                                range = null, )
                            ], 
                        template = gb_retailapi_client.models.rule_template.RuleTemplate(
                            name = '', 
                            enable_exact_matching = True, 
                            sections = [
                                gb_retailapi_client.models.rule_template_section.RuleTemplateSection(
                                    zone_id = 56, 
                                    name = '', 
                                    zone_content = '', 
                                    zone_type = 'QUERY', )
                                ], ), 
                        boosted_product_buckets = [
                            gb_retailapi_client.models.boosted_product_bucket.BoostedProductBucket(
                                products = [
                                    ''
                                    ], )
                            ], 
                        pinned_refinements = [
                            gb_retailapi_client.models.pinned_refinement.PinnedRefinement(
                                navigation = '', 
                                refinements = [
                                    gb_retailapi_client.models.refinement.Refinement(
                                        value = '', 
                                        priority = 56, )
                                    ], )
                            ], 
                        message_type = 'UPDATE', 
                        type = 'REGULAR', 
                        variants = [
                            gb_retailapi_client.models.experiment_variant.ExperimentVariant(
                                name = '', 
                                rule_variant = gb_retailapi_client.models.rule_variant.RuleVariant(
                                    biasing_profile_name = '', 
                                    included_navigations = [
                                        ''
                                        ], 
                                    template = gb_retailapi_client.models.rule_template.RuleTemplate(
                                        name = '', 
                                        enable_exact_matching = True, 
                                        sections = [
                                            gb_retailapi_client.models.rule_template_section.RuleTemplateSection(
                                                zone_id = 56, 
                                                name = '', 
                                                zone_content = '', 
                                                zone_type = 'QUERY', )
                                            ], ), 
                                    boosted_product_buckets = [
                                        gb_retailapi_client.models.boosted_product_bucket.BoostedProductBucket(
                                            products = [
                                                ''
                                                ], )
                                        ], 
                                    pinned_refinements = [
                                        gb_retailapi_client.models.pinned_refinement.PinnedRefinement(
                                            navigation = '', 
                                            refinements = [
                                                gb_retailapi_client.models.refinement.Refinement(
                                                    value = '', 
                                                    priority = 56, )
                                                ], )
                                        ], 
                                    sort = gb_retailapi_client.models.sort.Sort(
                                        field = '', 
                                        order = null, ), 
                                    value_filters = [
                                        gb_retailapi_client.models.value_filter.ValueFilter(
                                            field = '', 
                                            value = '', 
                                            number_value = 1.337, 
                                            exclude = True, 
                                            type = null, )
                                        ], 
                                    search_filters = [
                                        gb_retailapi_client.models.search_filter.SearchFilter(
                                            value = '', )
                                        ], 
                                    range_filters = [
                                        gb_retailapi_client.models.range_filter.RangeFilter(
                                            field = '', 
                                            range = null, )
                                        ], ), 
                                variant_trigger_percentage = 56, )
                            ], )
                    ]
            )
        else:
            return Overwrites(
                rules = [
                    gb_retailapi_client.models.rule_configuration.RuleConfiguration(
                        rule_in_experiment = True, 
                        id = 56, 
                        name = '', 
                        area_id = 56, 
                        priority = 56, 
                        enabled = True, 
                        active_hours_enabled = True, 
                        active_from = 56, 
                        active_to = 56, 
                        trigger_sets = [
                            gb_retailapi_client.models.trigger_set.TriggerSet(
                                query_pattern_triggers = [
                                    gb_retailapi_client.models.query_pattern_trigger.QueryPatternTrigger(
                                        type = 'CONTAINS', 
                                        values = [
                                            ''
                                            ], 
                                        patterns = [
                                            gb_retailapi_client.models.pattern.Pattern()
                                            ], )
                                    ], 
                                selected_refinement_triggers = [
                                    gb_retailapi_client.models.selected_refinement_trigger.SelectedRefinementTrigger(
                                        field = '', 
                                        value = '', 
                                        range = gb_retailapi_client.models.range.Range(
                                            low = 1.337, 
                                            high = 1.337, ), 
                                        type = 'RANGE', )
                                    ], 
                                custom_parameter_triggers = [
                                    gb_retailapi_client.models.custom_parameter_trigger.CustomParameterTrigger(
                                        key = '', 
                                        value = '', )
                                    ], )
                            ], 
                        biasing_profile_name = '', 
                        sort = gb_retailapi_client.models.sort.Sort(
                            field = '', 
                            order = null, ), 
                        included_navigations = [
                            ''
                            ], 
                        value_filters = [
                            gb_retailapi_client.models.value_filter.ValueFilter(
                                field = '', 
                                value = '', 
                                number_value = 1.337, 
                                exclude = True, 
                                type = null, )
                            ], 
                        search_filters = [
                            gb_retailapi_client.models.search_filter.SearchFilter(
                                value = '', )
                            ], 
                        range_filters = [
                            gb_retailapi_client.models.range_filter.RangeFilter(
                                field = '', 
                                range = null, )
                            ], 
                        template = gb_retailapi_client.models.rule_template.RuleTemplate(
                            name = '', 
                            enable_exact_matching = True, 
                            sections = [
                                gb_retailapi_client.models.rule_template_section.RuleTemplateSection(
                                    zone_id = 56, 
                                    name = '', 
                                    zone_content = '', 
                                    zone_type = 'QUERY', )
                                ], ), 
                        boosted_product_buckets = [
                            gb_retailapi_client.models.boosted_product_bucket.BoostedProductBucket(
                                products = [
                                    ''
                                    ], )
                            ], 
                        pinned_refinements = [
                            gb_retailapi_client.models.pinned_refinement.PinnedRefinement(
                                navigation = '', 
                                refinements = [
                                    gb_retailapi_client.models.refinement.Refinement(
                                        value = '', 
                                        priority = 56, )
                                    ], )
                            ], 
                        message_type = 'UPDATE', 
                        type = 'REGULAR', 
                        variants = [
                            gb_retailapi_client.models.experiment_variant.ExperimentVariant(
                                name = '', 
                                rule_variant = gb_retailapi_client.models.rule_variant.RuleVariant(
                                    biasing_profile_name = '', 
                                    included_navigations = [
                                        ''
                                        ], 
                                    template = gb_retailapi_client.models.rule_template.RuleTemplate(
                                        name = '', 
                                        enable_exact_matching = True, 
                                        sections = [
                                            gb_retailapi_client.models.rule_template_section.RuleTemplateSection(
                                                zone_id = 56, 
                                                name = '', 
                                                zone_content = '', 
                                                zone_type = 'QUERY', )
                                            ], ), 
                                    boosted_product_buckets = [
                                        gb_retailapi_client.models.boosted_product_bucket.BoostedProductBucket(
                                            products = [
                                                ''
                                                ], )
                                        ], 
                                    pinned_refinements = [
                                        gb_retailapi_client.models.pinned_refinement.PinnedRefinement(
                                            navigation = '', 
                                            refinements = [
                                                gb_retailapi_client.models.refinement.Refinement(
                                                    value = '', 
                                                    priority = 56, )
                                                ], )
                                        ], 
                                    sort = gb_retailapi_client.models.sort.Sort(
                                        field = '', 
                                        order = null, ), 
                                    value_filters = [
                                        gb_retailapi_client.models.value_filter.ValueFilter(
                                            field = '', 
                                            value = '', 
                                            number_value = 1.337, 
                                            exclude = True, 
                                            type = null, )
                                        ], 
                                    search_filters = [
                                        gb_retailapi_client.models.search_filter.SearchFilter(
                                            value = '', )
                                        ], 
                                    range_filters = [
                                        gb_retailapi_client.models.range_filter.RangeFilter(
                                            field = '', 
                                            range = null, )
                                        ], ), 
                                variant_trigger_percentage = 56, )
                            ], )
                    ],
        )
        """

    def testOverwrites(self):
        """Test Overwrites"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
