# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from gb_retailapi_client.models.filter_parameter import FilterParameter  # noqa: E501

class TestFilterParameter(unittest.TestCase):
    """FilterParameter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FilterParameter:
        """Test FilterParameter
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FilterParameter`
        """
        model = FilterParameter()  # noqa: E501
        if include_optional:
            return FilterParameter(
                field = '0',
                value = '',
                exclude = True,
                derived_from_product = True
            )
        else:
            return FilterParameter(
                field = '0',
                exclude = True,
                derived_from_product = True,
        )
        """

    def testFilterParameter(self):
        """Test FilterParameter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
