# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import re  # noqa: F401
import io
import warnings

from pydantic import validate_arguments, ValidationError

from typing_extensions import Annotated
from pydantic import Field, StrictStr

from typing import Optional

from gb_retailapi_client.models.identity import Identity
from gb_retailapi_client.models.merchandiser import Merchandiser
from gb_retailapi_client.models.request import Request
from gb_retailapi_client.models.search_results import SearchResults

from gb_retailapi_client.api_client import ApiClient
from gb_retailapi_client.api_response import ApiResponse
from gb_retailapi_client.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class AutocompleteApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    def autocompletesearch(self, x_groupby_customer_id : Annotated[StrictStr, Field(..., description="Header on incoming HTTP requests that is populated by the API gateway and indicates the customer ID.")], identity : Identity, merchandiser : Merchandiser, request : Annotated[Optional[Request], Field(description="Object which is represent autocomplete request and encapsulate all passed parameters. ")] = None, **kwargs) -> SearchResults:  # noqa: E501
        """autocompletesearch  # noqa: E501

        A simple request used to get completes the specified prefix with keyword suggestions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.autocompletesearch(x_groupby_customer_id, identity, merchandiser, request, async_req=True)
        >>> result = thread.get()

        :param x_groupby_customer_id: Header on incoming HTTP requests that is populated by the API gateway and indicates the customer ID. (required)
        :type x_groupby_customer_id: str
        :param identity: (required)
        :type identity: Identity
        :param merchandiser: (required)
        :type merchandiser: Merchandiser
        :param request: Object which is represent autocomplete request and encapsulate all passed parameters. 
        :type request: Request
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: SearchResults
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the autocompletesearch_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.autocompletesearch_with_http_info(x_groupby_customer_id, identity, merchandiser, request, **kwargs)  # noqa: E501

    @validate_arguments
    def autocompletesearch_with_http_info(self, x_groupby_customer_id : Annotated[StrictStr, Field(..., description="Header on incoming HTTP requests that is populated by the API gateway and indicates the customer ID.")], identity : Identity, merchandiser : Merchandiser, request : Annotated[Optional[Request], Field(description="Object which is represent autocomplete request and encapsulate all passed parameters. ")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """autocompletesearch  # noqa: E501

        A simple request used to get completes the specified prefix with keyword suggestions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.autocompletesearch_with_http_info(x_groupby_customer_id, identity, merchandiser, request, async_req=True)
        >>> result = thread.get()

        :param x_groupby_customer_id: Header on incoming HTTP requests that is populated by the API gateway and indicates the customer ID. (required)
        :type x_groupby_customer_id: str
        :param identity: (required)
        :type identity: Identity
        :param merchandiser: (required)
        :type merchandiser: Merchandiser
        :param request: Object which is represent autocomplete request and encapsulate all passed parameters. 
        :type request: Request
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(SearchResults, status_code(int), headers(HTTPHeaderDict))
        """

        _hosts = [
            'https://autocomplete.{environment}.groupbycloud.com'
        ]
        _host = _hosts[0]
        if kwargs.get('_host_index'):
            _host_index = int(kwargs.get('_host_index'))
            if _host_index < 0 or _host_index >= len(_hosts):
                raise ApiValueError(
                    "Invalid host index. Must be 0 <= index < %s"
                    % len(_host)
                )
            _host = _hosts[_host_index]
        _params = locals()

        _all_params = [
            'x_groupby_customer_id',
            'identity',
            'merchandiser',
            'request'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params and _key != "_host_index":
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method autocompletesearch" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('request') is not None:  # noqa: E501
            _query_params.append(('request', _params['request']))

        if _params.get('identity') is not None:  # noqa: E501
            _query_params.append(('identity', _params['identity']))

        if _params.get('merchandiser') is not None:  # noqa: E501
            _query_params.append(('merchandiser', _params['merchandiser']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        if _params['x_groupby_customer_id']:
            _header_params['X-Groupby-Customer-Id'] = _params['x_groupby_customer_id']

        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['GroupByIncEmployee', 'ClientKey']  # noqa: E501

        _response_types_map = {
            '200': "SearchResults",
            '400': "ErrorResponse",
        }

        return self.api_client.call_api(
            '/api/request', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            _host=_host,
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
