# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import re  # noqa: F401
import io
import warnings

from pydantic import validate_arguments, ValidationError

from typing_extensions import Annotated
from pydantic import Field, StrictStr

from gb_retailapi_client.models.predict_results import PredictResults
from gb_retailapi_client.models.recommendations_request import RecommendationsRequest

from gb_retailapi_client.api_client import ApiClient
from gb_retailapi_client.api_response import ApiResponse
from gb_retailapi_client.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class RecommendationsAPIApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    def predict(self, x_groupby_customer_id : Annotated[StrictStr, Field(..., description="Custom HTTP header which may contain tenant name. Used to define a client by its name.")], recommendations_request : Annotated[RecommendationsRequest, Field(..., description="Request that should be populated to configure a recommendations API call made by the client.")], **kwargs) -> PredictResults:  # noqa: E501
        """(Deprecated) Provide Recommendations AI functionality.  # noqa: E501

        Perform a recommendation request against the GroupBy Retail Recommendations API.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.predict(x_groupby_customer_id, recommendations_request, async_req=True)
        >>> result = thread.get()

        :param x_groupby_customer_id: Custom HTTP header which may contain tenant name. Used to define a client by its name. (required)
        :type x_groupby_customer_id: str
        :param recommendations_request: Request that should be populated to configure a recommendations API call made by the client. (required)
        :type recommendations_request: RecommendationsRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: PredictResults
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the predict_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.predict_with_http_info(x_groupby_customer_id, recommendations_request, **kwargs)  # noqa: E501

    @validate_arguments
    def predict_with_http_info(self, x_groupby_customer_id : Annotated[StrictStr, Field(..., description="Custom HTTP header which may contain tenant name. Used to define a client by its name.")], recommendations_request : Annotated[RecommendationsRequest, Field(..., description="Request that should be populated to configure a recommendations API call made by the client.")], **kwargs) -> ApiResponse:  # noqa: E501
        """(Deprecated) Provide Recommendations AI functionality.  # noqa: E501

        Perform a recommendation request against the GroupBy Retail Recommendations API.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.predict_with_http_info(x_groupby_customer_id, recommendations_request, async_req=True)
        >>> result = thread.get()

        :param x_groupby_customer_id: Custom HTTP header which may contain tenant name. Used to define a client by its name. (required)
        :type x_groupby_customer_id: str
        :param recommendations_request: Request that should be populated to configure a recommendations API call made by the client. (required)
        :type recommendations_request: RecommendationsRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(PredictResults, status_code(int), headers(HTTPHeaderDict))
        """

        warnings.warn("POST /api/predict is deprecated.", DeprecationWarning)

        _hosts = [
            'https://recsapi.{environment}.groupbycloud.com'
        ]
        _host = _hosts[0]
        if kwargs.get('_host_index'):
            _host_index = int(kwargs.get('_host_index'))
            if _host_index < 0 or _host_index >= len(_hosts):
                raise ApiValueError(
                    "Invalid host index. Must be 0 <= index < %s"
                    % len(_host)
                )
            _host = _hosts[_host_index]
        _params = locals()

        _all_params = [
            'x_groupby_customer_id',
            'recommendations_request'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params and _key != "_host_index":
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method predict" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        if _params['x_groupby_customer_id']:
            _header_params['X-Groupby-Customer-Id'] = _params['x_groupby_customer_id']

        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['recommendations_request'] is not None:
            _body_params = _params['recommendations_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['GroupByIncEmployee', 'ClientKey']  # noqa: E501

        _response_types_map = {
            '200': "PredictResults",
            '400': "RecommendationsErrorResponse",
            '403': "RecommendationsErrorResponse",
            '404': "RecommendationsErrorResponse",
            '500': "RecommendationsErrorResponse",
        }

        return self.api_client.call_api(
            '/api/predict', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            _host=_host,
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def predict_v2(self, x_groupby_customer_id : Annotated[StrictStr, Field(..., description="Custom HTTP header which may contain tenant name. Used to define a client by its name.")], recommendations_request : Annotated[RecommendationsRequest, Field(..., description="Request that should be populated to configure a recommendations API call made by the client.")], **kwargs) -> PredictResults:  # noqa: E501
        """Provide Recommendations AI functionality.  # noqa: E501

        Perform a recommendation request against the GroupBy Retail Recommendations API.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.predict_v2(x_groupby_customer_id, recommendations_request, async_req=True)
        >>> result = thread.get()

        :param x_groupby_customer_id: Custom HTTP header which may contain tenant name. Used to define a client by its name. (required)
        :type x_groupby_customer_id: str
        :param recommendations_request: Request that should be populated to configure a recommendations API call made by the client. (required)
        :type recommendations_request: RecommendationsRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: PredictResults
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the predict_v2_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.predict_v2_with_http_info(x_groupby_customer_id, recommendations_request, **kwargs)  # noqa: E501

    @validate_arguments
    def predict_v2_with_http_info(self, x_groupby_customer_id : Annotated[StrictStr, Field(..., description="Custom HTTP header which may contain tenant name. Used to define a client by its name.")], recommendations_request : Annotated[RecommendationsRequest, Field(..., description="Request that should be populated to configure a recommendations API call made by the client.")], **kwargs) -> ApiResponse:  # noqa: E501
        """Provide Recommendations AI functionality.  # noqa: E501

        Perform a recommendation request against the GroupBy Retail Recommendations API.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.predict_v2_with_http_info(x_groupby_customer_id, recommendations_request, async_req=True)
        >>> result = thread.get()

        :param x_groupby_customer_id: Custom HTTP header which may contain tenant name. Used to define a client by its name. (required)
        :type x_groupby_customer_id: str
        :param recommendations_request: Request that should be populated to configure a recommendations API call made by the client. (required)
        :type recommendations_request: RecommendationsRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(PredictResults, status_code(int), headers(HTTPHeaderDict))
        """

        _hosts = [
            'https://recsapi.{environment}.groupbycloud.com'
        ]
        _host = _hosts[0]
        if kwargs.get('_host_index'):
            _host_index = int(kwargs.get('_host_index'))
            if _host_index < 0 or _host_index >= len(_hosts):
                raise ApiValueError(
                    "Invalid host index. Must be 0 <= index < %s"
                    % len(_host)
                )
            _host = _hosts[_host_index]
        _params = locals()

        _all_params = [
            'x_groupby_customer_id',
            'recommendations_request'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params and _key != "_host_index":
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method predict_v2" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        if _params['x_groupby_customer_id']:
            _header_params['X-Groupby-Customer-Id'] = _params['x_groupby_customer_id']

        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['recommendations_request'] is not None:
            _body_params = _params['recommendations_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['GroupByIncEmployee', 'ClientKey']  # noqa: E501

        _response_types_map = {
            '200': "PredictResults",
            '400': "RecommendationsErrorResponse",
            '403': "RecommendationsErrorResponse",
            '404': "RecommendationsErrorResponse",
            '500': "RecommendationsErrorResponse",
        }

        return self.api_client.call_api(
            '/api/recommendation', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            _host=_host,
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
