# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class BiasDtoStrengthDto(str, Enum):
    """
    The amount the bias will affect the search results.
    """

    """
    allowed enum values
    """
    ABSOLUTE_INCREASE = 'ABSOLUTE_INCREASE'
    STRONG_INCREASE = 'STRONG_INCREASE'
    MEDIUM_INCREASE = 'MEDIUM_INCREASE'
    WEAK_INCREASE = 'WEAK_INCREASE'
    LEAVE_UNCHANGED = 'LEAVE_UNCHANGED'
    WEAK_DECREASE = 'WEAK_DECREASE'
    MEDIUM_DECREASE = 'MEDIUM_DECREASE'
    STRONG_DECREASE = 'STRONG_DECREASE'
    ABSOLUTE_DECREASE = 'ABSOLUTE_DECREASE'

    @classmethod
    def from_json(cls, json_str: str) -> BiasDtoStrengthDto:
        """Create an instance of BiasDtoStrengthDto from a JSON string"""
        return BiasDtoStrengthDto(json.loads(json_str))


