# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class MessageType(str, Enum):
    """
    MessageType
    """

    """
    allowed enum values
    """
    UPDATE = 'UPDATE'
    DELETE = 'DELETE'
    CREATE = 'CREATE'
    UNRECOGNIZED = 'UNRECOGNIZED'

    @classmethod
    def from_json(cls, json_str: str) -> MessageType:
        """Create an instance of MessageType from a JSON string"""
        return MessageType(json.loads(json_str))


