# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class Promotion(BaseModel):
    """
    The promotions applied to the product. A maximum of 10 values are allowed per product.  # noqa: E501
    """
    promotion_id: Optional[StrictStr] = Field(None, alias="promotionId", description="ID of the promotion. For example, 'free gift'. Length limit of 128 characters.")
    __properties = ["promotionId"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Promotion:
        """Create an instance of Promotion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Promotion:
        """Create an instance of Promotion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Promotion.parse_obj(obj)

        _obj = Promotion.parse_obj({
            "promotion_id": obj.get("promotionId")
        })
        return _obj


