# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class QueryPatternTriggerType(str, Enum):
    """
    QueryPatternTriggerType
    """

    """
    allowed enum values
    """
    CONTAINS = 'CONTAINS'
    ENDS_WITH = 'ENDS_WITH'
    REGEX = 'REGEX'
    STARTS_WITH = 'STARTS_WITH'
    MATCHES = 'MATCHES'

    @classmethod
    def from_json(cls, json_str: str) -> QueryPatternTriggerType:
        """Create an instance of QueryPatternTriggerType from a JSON string"""
        return QueryPatternTriggerType(json.loads(json_str))


