# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, StrictBool, StrictStr, conlist
from gb_retailapi_client.models.rule_template_section import RuleTemplateSection

class RuleTemplate(BaseModel):
    """
    RuleTemplate
    """
    name: StrictStr = Field(...)
    enable_exact_matching: StrictBool = Field(..., alias="enableExactMatching")
    sections: conlist(RuleTemplateSection) = Field(...)
    __properties = ["name", "enableExactMatching", "sections"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RuleTemplate:
        """Create an instance of RuleTemplate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in sections (list)
        _items = []
        if self.sections:
            for _item in self.sections:
                if _item:
                    _items.append(_item.to_dict())
            _dict['sections'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RuleTemplate:
        """Create an instance of RuleTemplate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RuleTemplate.parse_obj(obj)

        _obj = RuleTemplate.parse_obj({
            "name": obj.get("name"),
            "enable_exact_matching": obj.get("enableExactMatching"),
            "sections": [RuleTemplateSection.from_dict(_item) for _item in obj.get("sections")] if obj.get("sections") is not None else None
        })
        return _obj


