# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class SelectedRefinementTriggerType(str, Enum):
    """
    SelectedRefinementTriggerType
    """

    """
    allowed enum values
    """
    RANGE = 'RANGE'
    VALUE = 'VALUE'
    NAVIGATION_SELECTED = 'NAVIGATION_SELECTED'

    @classmethod
    def from_json(cls, json_str: str) -> SelectedRefinementTriggerType:
        """Create an instance of SelectedRefinementTriggerType from a JSON string"""
        return SelectedRefinementTriggerType(json.loads(json_str))


