# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr
from gb_retailapi_client.models.range import Range
from gb_retailapi_client.models.selected_refinement_trigger_type import SelectedRefinementTriggerType

class SelectedRefinementTrigger(BaseModel):
    """
    SelectedRefinementTrigger
    """
    field: StrictStr = Field(...)
    value: StrictStr = Field(...)
    range: Range = Field(...)
    type: SelectedRefinementTriggerType = Field(...)
    __properties = ["field", "value", "range", "type"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SelectedRefinementTrigger:
        """Create an instance of SelectedRefinementTrigger from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of range
        if self.range:
            _dict['range'] = self.range.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SelectedRefinementTrigger:
        """Create an instance of SelectedRefinementTrigger from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SelectedRefinementTrigger.parse_obj(obj)

        _obj = SelectedRefinementTrigger.parse_obj({
            "field": obj.get("field"),
            "value": obj.get("value"),
            "range": Range.from_dict(obj.get("range")) if obj.get("range") is not None else None,
            "type": obj.get("type")
        })
        return _obj


