# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class SortDtoOrderDto(str, Enum):
    """
    Order the products will appear in
    """

    """
    allowed enum values
    """
    ASCENDING = 'Ascending'
    DESCENDING = 'Descending'

    @classmethod
    def from_json(cls, json_str: str) -> SortDtoOrderDto:
        """Create an instance of SortDtoOrderDto from a JSON string"""
        return SortDtoOrderDto(json.loads(json_str))


