# coding: utf-8

"""
    GroupBy Retail

    GroupBy Retail API

    The version of the OpenAPI document: 0.0
    Contact: ops@groupbyinc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ValueFilterValueFilterType(str, Enum):
    """
    ValueFilterValueFilterType
    """

    """
    allowed enum values
    """
    TEXTUAL = 'TEXTUAL'
    NUMERIC = 'NUMERIC'

    @classmethod
    def from_json(cls, json_str: str) -> ValueFilterValueFilterType:
        """Create an instance of ValueFilterValueFilterType from a JSON string"""
        return ValueFilterValueFilterType(json.loads(json_str))


